baseURL = 'https://github.com/pushkalsingh/tohfa'
languageCode = 'en-us'
title = 'Art by Moniika'
theme = 'galleriesdeluxe'

# Vital for images in GitHub subfolders
canonifyURLs = true
relativeURLs = false
