baseURL = 'https://github.com/pushkalsingh/tohfa'
languageCode = 'en-us'
title = 'My Photo Gallery'
theme = 'github.com/bep/galleriesdeluxe'

[module]
  [[module.imports]]
    path = 'github.com/bep/galleriesdeluxe'
